project_id = "lnhkjjdxoilypcttemau"

[functions.drama-remix]
verify_jwt = false

[functions.public-share]
verify_jwt = false

[functions.remix-vote]
verify_jwt = false

[functions.usage-check]
verify_jwt = false
